<?php

namespace AppBundle\Repository;

/**
 * BlindLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlindLevelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $query = $this->createQueryBuilder('b')
            ->addOrderBy('a.level ASC')
            ->getQuery();
        
        return $query->getResult();
    }
}
