<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Tournament;
/**
 * TournamentRankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRankingRepository extends EntityRepository
{
    public function findByTournament(Tournament $tournament)
    {
        $query = $this->createQueryBuilder('r')
            ->join('r.player', 'p')
            ->where('r.tournament = :tournament')
            ->setParameter('tournament', $tournament)
            ->orderBy('r.rank', 'ASC')
            ->addOrderBy('p.nickname', 'ASC')
            ->getQuery();
        
        return $query->getResult();
    }
}
