<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Tournament;
use AppBundle\Entity\Player;
/**
 * TournamentRankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRankingRepository extends EntityRepository
{
    public function findByTournament(Tournament $tournament)
    {
        $query = $this->createQueryBuilder('r')
            ->join('r.player', 'p')
            ->where('r.tournament = :tournament')
            ->setParameter('tournament', $tournament)
            ->orderBy('r.rank', 'ASC')
            ->addOrderBy('p.nickname', 'ASC')
            ->getQuery();
        
        return $query->getResult();
    }
    
    /**
     * Löscht Einträge anhand des Turniers und einer übergebenen Liste von Spielern
     * 
     * @param Tournament $tournament
     * @param array $playerList List of Player
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function deleteByTournamentAndPlayerList(Tournament $tournament, array $playerList)
    {
        $query = $this->createQueryBuilder('r')
            ->delete()
            ->where('r.tournament = :tournament')
            ->setParameter('tournament', $tournament)
            ->andWhere('r.player IN (:playerList)')
            ->setParameter('playerList', $playerList)
            ->getQuery();
        
        return $query->execute();
    }
}
