<?php

namespace AppBundle\Repository;

/**
 * TournamentStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
