administration:
    resource: "@AppBundle/Controller/Administration/"
    type:     annotation 
    prefix:   /administration

live:
    resource: "@AppBundle/Controller/Live/"
    type:     annotation 
    prefix:   /live

dmx:
    resource: "@AppBundle/Controller/DmxController.php"
    type:     annotation 
    
bpn_default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation 
    
bpn_player:
    resource: "@AppBundle/Controller/PlayerController.php"
    type:     annotation 

bpn_location:
    resource: "@AppBundle/Controller/LocationController.php"
    type:     annotation 

bpn_event:
    resource: "@AppBundle/Controller/EventController.php"
    type:     annotation 

bpn_tournament:
    resource: "@AppBundle/Controller/TournamentController.php"
    type:     annotation 

bpn_table:
    resource: "@AppBundle/Controller/TableController.php"
    type:     annotation 

bpn_ajax:
    resource: "@AppBundle/Controller/AjaxController.php"
    type:     annotation 
    