<?php

namespace AppBundle\Entity;

/**
 * AnnualRankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnualRankingRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLastGroupByPlayer()
	{
		$query = $this->createQueryBuilder('a')
			->groupBy('a.player')
			->having('a.date =  MAX(a.date)')
			->orderBy('a.sumPoints', 'DESC')
			->getQuery();
		
		return $query->getResult();
	}
}
