<?php

namespace Reu\Pokernight\AppBundle\Entity;

/**
 * TableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableRepository extends \Doctrine\ORM\EntityRepository
{
	public function findMaxNumberByTournament(Tournament $tournament)
	{
		$query = $this->createQueryBuilder('t')
			->select('MAX(t.number)')
			->where('t.tournament = ?1')
			->setParameter(1, $tournament)
			->getQuery();
		
		return (int)$query->getSingleScalarResult();
	}
}
