<?php

namespace Reu\Pokernight\AppBundle\Entity;

/**
 * TournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Gibt die letzten 5 Hauptevents (Pokernights) vor aktuellem Zeitpunk zurück
	 */
	public function findAnnualRankingRelevant()
	{
		$query = $this->createQueryBuilder('t')
			->where('t.mainTournament = true')
			->andWhere('t.date < CURRENT_TIMESTAMP()')
			->orderBy('t.date','ASC')
			->setMaxResults(5)
			->getQuery();
		
		return $query->getResult();
	}
}
